#!/bin/bash

###################### Script to properly store the fastqc files #########################
#			Similarly to organize_fastq.sh							 #
##########################################################################################


FASTQC_DIR="/fastqc_directory/" #Directory containing the fastqc files generated by fastqc.sh
TARGET_DIR="/path_to_directory_where_you_want_your_fastqc/" #Example: "/project_name/data/raw_data/zebrafish/RNA/name_experiment/"

cd "$FASTQC_DIR"


# Loop through all subdirectories in the current directory
for subfolder in */; do
    # Remove trailing slash
    subfolder=${subfolder%/}

    # Extract the base name (everything before _R1_001 or _R2_001)
    if [[ "$subfolder" == *"_R1_001"* ]]; then
        subfolder_base=${subfolder%%_R1_001*}
    elif [[ "$subfolder" == *"_R2_001"* ]]; then
        subfolder_base=${subfolder%%_R2_001*}
    else
        # If neither pattern is found, use the whole subfolder name
        subfolder_base="$subfolder"
    fi

    # Create corresponding subdirectory in target location
    mkdir -p "$TARGET_DIR/$subfolder_base"

    # Copy fastqc file to target directory
    if [ -d "$subfolder" ]; then
        echo "Processing $subfolder..."

        # Go into the subfolder and find fastqc files
        fastqc_files=$(find "$subfolder" -name "*fastqc.html*")

        if [ -n "$fastqc_files" ]; then
            # Copy the fastqc files to the corresponding target subdirectory
            for file in $fastqc_files; do
                cp "$file" "$TARGET_DIR/$subfolder_base/"
                echo "  Copied $(basename "$file") to $TARGET_DIR/$subfolder_base/"
            done
        else
            echo "  No fastqc files found in $subfolder"
        fi
    fi
done

echo "File copying complete!"
